apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /rabbitmq/ampq
        backend:
          serviceName: rabbitmq-backend
          servicePort: 5672
      - path: /rabbitmq
        backend:
          serviceName: rabbitmq-backend
          servicePort: 15672