apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
     labels:
       app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        command:
        - mongod
        - --replSet
        - rs0
        - --bind_ip
        - 0.0.0.0
        ports:
        - containerPort: 27017
          name: peer
      - name: init-mongo
        image: mongo:3
        command:
        - /bin/bash
        - /config/init.sh
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: mongo-init